# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: HaiDan Sign

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    # UTC 时间 PRC每天凌晨2点、上午10点和晚上4点执行一次
    - cron: 0 18,2,8 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run
      env:
        HAIDAN_UID: Mzg2MTI%3D
        HAIDAN_PASS: 55883369ff46541a9de556a23f5953ce
        HAIDAN_LOGIN: bm9wZQ%3D%3D
        HAIDAN_MULTI: ${{ secrets.HAIDAN_MULTI }}
        HAIDAN_PRIVACY: ${{ secrets.HAIDAN_PRIVACY }}
      run: |
        python main.py
